### PR TITLE
Update the used versions of Docker, Git and docker-compose

### PR DESCRIPTION
**Pull request by ZPascal**
Hi @jhunt,

as discussed [here](https://github.com/jhunt/containers-boshrelease/issues/14), I have prepared an appropriate PR and updated Docker, Git, docker-compose. 

Furthermore, I created a dev release on my side and consumed it accordingly in a CF dev landscape. 
FYI: In the process, we noticed that we could not consume the Docker and Jumpbox blobs (jobs) (not public available or no permissions) and had to clean up the release manifest directory accordingly for this.

### CODE REVIEW

**Comment by ZPascal** [comment]
Hi @jhunt, I'm not sure why the job is failing at this time, but the PR is ready for a review. Can you please take a look at the PR?

**Comment by ZPascal** [comment]
Hi @jhunt, could you please retrigger the failed build release job?

**Comment by jhunt** [comment]
Bumped and re-ran, still failing.  This time it's not CI/CD-related.  It's mad about the missing blobs.  Let me see if I can track those down and get them uploaded.

**Comment by ZPascal** [comment]
@jhunt Do you have any news to upload the blobs? Do you need to support from my side?

**Comment by ZPascal** [comment]
Hi @jhunt, any news from your side?

**Pull request merged**
